# Generated by Django 3.2.9 on 2021-11-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '패스트캠퍼스 태그', 'verbose_name_plural': '패스트캠퍼스 태그'},
        ),
    ]
