# Generated by Django 3.2.9 on 2021-11-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_alter_fcuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시간'),
        ),
    ]
